<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>TinkerCAN.Can</AssemblyName>
    <RootNamespace>TinkerCAN.Can</RootNamespace>
    <Optimize>true</Optimize>
  </PropertyGroup>
</Project>
